on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test greeting action
    steps:
      - name: gday step
        id: gday
        uses: bcumming/hw-action@v1.2
        with:
          who-to-greet: 'Ben from Brisbane'
      # Use the output from the `gday` step
      - name: Get the output time
        run: echo "The time was ${{ steps.gday.outputs.time }}"
